FROM zabbix/zabbix-proxy-sqlite3:ubuntu-5.0-latest
USER root
RUN apt update
RUN apt install unzip curl wget gnupg2 alien libaio1 tdsodbc libgtk2.0-0 libgtk-3-0 snmp snmp-mibs-downloader vim -y
RUN echo mibs +ALL >> /etc/snmp/snmp.conf
#MYSQL
ADD https://dev.mysql.com/get/Downloads/Connector-ODBC/8.0/mysql-connector-odbc-8.0.30-linux-glibc2.27-x86-64bit.tar.gz tmp/
RUN tar -xvf tmp/mysql-connector-odbc-8.0.30-linux-glibc2.27-x86-64bit.tar.gz -C /tmp \
&& cp /tmp/mysql-connector-odbc-8.0.30-linux-glibc2.27-x86-64bit/bin/myodbc-installer /usr/bin \
&& cp -R /tmp/mysql-connector-odbc-8.0.30-linux-glibc2.27-x86-64bit/lib/* /usr/local/lib \
&& rm -rf tmp/mysql-connector-odbc-8.0.30-linux-glibc2.27-x86-64bit.tar.gz
#ADD /home/bds/odbc/mysql-connector-odbc-8.0.30/bin/ /usr/bin/
#ADD /home/bds/odbc/mysql-connector-odbc-8.0.30/lib/ /usr/local/lib/
RUN myodbc-installer -a -d -n "MySQL ODBC 8.0 Driver" -t "Driver=/usr/local/lib/libmyodbc8w.so" \
&& myodbc-installer -a -d -n "MySQL ODBC 8.0" -t "Driver=/usr/local/lib/libmyodbc8a.so"
RUN apt install odbc-mariadb -y
#MSSQL
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
ADD https://packages.microsoft.com/config/ubuntu/22.04/prod.list /etc/apt/sources.list.d/msprod.list
RUN apt update && ACCEPT_EULA=Y apt install mssql-tools unixodbc-dev -y
#POSTGRES
RUN apt install odbc-postgresql -y
#ORACLE
RUN mkdir /opt/oracle
ADD https://download.oracle.com/otn_software/linux/instantclient/instantclient-basic-linuxx64.zip /tmp
ADD https://download.oracle.com/otn_software/linux/instantclient/instantclient-odbc-linuxx64.zip /tmp
RUN unzip /tmp/instantclient-basic-linuxx64.zip -d /opt/oracle \
&& unzip /tmp/instantclient-odbc-linuxx64.zip -d /opt/oracle
RUN sh -c 'cd /opt/oracle/instantclient_21_6; ./odbc_update_ini.sh /.'
RUN sh -c "echo /opt/oracle/instantclient_21_6 > /etc/ld.so.conf.d/oracle-instantclient.conf"
RUN ldconfig
# RUN wget https://download.oracle.com/otn_software/linux/instantclient/1916000/oracle-instantclient19.16-basiclite-19.16.0.0.0-1.x86_64.rpm
# RUN alien -i oracle-instantclient19.16-basiclite-19.16.0.0.0-1.x86_64.rpm 
# RUN sh -c 'echo /usr/lib/oracle/19.16/client64/lib/ > /etc/ld.so.conf.d/oracle.conf'
# RUN ldconfig
# https://download.oracle.com/otn_software/linux/instantclient/217000/instantclient-odbc-linux.x64-21.7.0.0.0dbru.zip


RUN echo "\
[DSN]\n\
Driver=ODBC Driver 17 for SQL Server \n\
Description=Descritor de conexao SQLServer \n\
Pooling = No \n\
Trace=Yes \n\
Encrypt=No \n\
Server=tcp:ip\instancia,1433 \n\
Database=master \n\
\n[DSN] \n\
Driver = Oracle 21 ODBC driver \n\
DSN = Oracle 21 ODBC driver \n\
ServerName = //ip:1521/instancia \n\
\n[DSN] \n\
Description     = MySQL \n\
Driver          = MySQL ODBC 8.0 Driver \n\
Server          = ip \n\
User            = usuario \n\
Password        = senha \n\
Database        = banco" >> /etc/odbc.ini 






# RUN dnf install w -y
# RUN wget ftp://ftp.unixodbc.org/pub/unixODBC/unixODBC-2.3.11.tar.gz
# #ODBC MYSQL
# RUN dnf install mysql-connector-odbc
# #ODBC POSTGRES
# RUN dnf install postgresql93-odbc.x86_64 postgresql93-odbc-debuginfo.x86_64 unixODBC
# #ODBC MSSQL
# RUN sudo su \ && curl https://packages.microsoft.com/config/rhel/8/prod.repo > /etc/dnf.repos.d/mssql-release.repo \
# && sudo ACCEPT_EULA=Y dnf install -y msodbcsql18 \
# && sudo ACCEPT_EULA=Y dnf install -y mssql-tools18 \
# && echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.bashrc \
# && source ~/.bashrc \
# %% sudo dnf install -y unixODBC-devel

