version: "3.3"
services:
 zabbix-proxy-v3:
 image: dockerglobalcare/globalcare:v3
 container_name: proxy
 hostname: proxy
 ports:
 - 192.168.0.35:10051:10051
 cap_add: ['NET_ADMIN']
 devices:
 - /dev/net/tun
 environment:
 - ZBX_HOSTNAME=latjussara.docker.prx.v.globalcare
 - ZBX_SERVER_HOST=192.168.54.3
 - ZBX_DEBUGLEVEL=3
 - ZBX_TIMEOUT=30
 - ZBX_PROXYLOCALBUFFER=1
 - ZBX_PROXYOFFLINEBUFFER=2
 - ZBX_CONFIGFREQUENCY=600
 - ZBX_STARTPOLLERS=15
 - ZBX_STARTPOLLERSUNREACHABLE=5
 - ZBX_STARTTRAPPERS=15
 - ZBX_STARTPINGERS=2
 - ZBX_STARTVMWARECOLLECTORS=1
 - ZBX_CACHESIZE=16M
 - ZBX_HISTORYCACHESIZE=32M
 - ZBX_HISTORYINDEXCACHESIZE=8M
 - ZBX_STARTVMWARECOLLECTORS=0
 - ZBX_VMWAREFREQUENCY=60
 - ZBX_VMWAREPERFFREQUENCY=60
 - ZBX_VMWARECACHESIZE=8M
 - ZBX_VMWARETIMEOUT=10
- TNS_ADMIN=/usr/lib/oracle/12.1/client64/network/admin
 volumes:
 - /opt/openvpn:/opt/openvpn
 - /opt/globalcare/scripts/externalscripts:/usr/lib/zabbix/externalscripts
### -
/opt/globalcare/tnsnames.ora:/usr/lib/oracle/12.1/client64/network/admin/tnsnames.ora
 - /etc/odbc.ini:/etc/odbc.ini
 - /etc/timezone:/etc/timezone:ro
 - /etc/localtime:/etc/localtime:ro
 restart: always
 networks:
 zbx-network:
 ipv4_address: 172.25.0.100
networks:
 zbx-network:
 ipam:
 driver: default
 config:
 - subnet: 172.25.0.0/24