version: '3.1'

networks:
  network-zabbix:
    driver: bridge

services:
  timescaledb:
    platform: linux/amd64
    container_name: pgsql
    image: timescale/timescaledb:latest-pg14
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=globalcare
      - POSTGRES_PASSWORD=zabbix
      - LANG=en_US.utf8
      - LANGUAGE=en_US.utf8
      - LC_ALL=en_US.utf8
      - LC_COLLATE=en_US.utf8
      - LC_CTYPE=en_US.utf8
      - TZ=GMT-3
    networks:
      - network-zabbix
    volumes:
      - /data/timescaledb:/var/lib/postgresql/data

  zabbix-server:
    container_name: zabbix-node01
    image: zabbix/zabbix-server-pgsql:alpine-6.2.0
    networks:
      - network-zabbix
    links:
      - timescaledb
    restart: always
    ports:
      - '10051:10051'
    volumes:
      - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
    environment:
      - DB_SERVER_HOST=pgsql
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=globalcare
      - POSTGRES_PASSWORD=zabbix
      - ZBX_SERVER_NAME=zsrv
      - ENABLE_TIMESCALEDB=true
      - ZBX_HANODENAME=zabbix-node01
      - ZBX_NODEADDRESS=zabbix-node01:10051
    depends_on:
      - timescaledb

  zabbix-server2:
    container_name: zabbix-node02
    image: zabbix/zabbix-server-pgsql:alpine-6.2.0
    networks:
      - network-zabbix
    links:
      - timescaledb
    restart: always
    ports:
      - '10052:10051'
    volumes:
      - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
    environment:
      - DB_SERVER_HOST=pgsql
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=globalcare
      - POSTGRES_PASSWORD=zabbix
      - ZBX_SERVER_NAME=zsrv
      - ENABLE_TIMESCALEDB=true
      - ZBX_HANODENAME=zabbix-node02
      - ZBX_NODEADDRESS=zabbix-node02:10051
    depends_on:
      - timescaledb

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-apache-pgsql:alpine-6.2.0
    networks:
      - network-zabbix
    links:
      - timescaledb
      - zabbix-server
      - zabbix-server2
    restart: always
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - DB_SERVER_HOST=pgsql
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=globalcare
      - POSTGRES_PASSWORD=zabbix
      - PHP_TZ=America/Sao_Paulo
      #- ZBX_SERVER_HOST=zabbix-server
    depends_on:
      - timescaledb
   
  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
      - network-zabbix
    links:
      - timescaledb
      - zabbix-server
      - zabbix-server2
      - zabbix-frontend
    restart: always
    ports:
      - '3000:3000'
    environment: 
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    depends_on:
      - timescaledb
      - zabbix-server
      - zabbix-server2

  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2:alpine-6.2.0
    user: root
    networks:
      - network-zabbix
    links:
      - zabbix-server
      - zabbix-server2
      - zabbix-frontend
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
    ports:
      - '10050:10050'
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=zabbix-node01,zabbix-node02