FROM node:14-slim AS build

ENV TZ="America/Sao_Paulo"

RUN apt-get update && \
  apt-get install -y wget gnupg git && \
  npm install -g pm2

WORKDIR /whatsapp-web.js
COPY ./base .
RUN npm install

# Estágio de execução
FROM node:14-slim AS runtime

ENV TZ="America/Sao_Paulo"

RUN apt-get update && \
  apt-get install -y wget gnupg git && \
  wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
  echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | tee /etc/apt/sources.list.d/google-chrome.list && \
  apt-get update && \
  apt-get install -y google-chrome-stable && \
  rm -rf /var/lib/apt/lists/*

COPY --from=build /whatsapp-web.js /whatsapp-web.js
WORKDIR /whatsapp-web.js

EXPOSE 4000
ENTRYPOINT [ "node", "compweb.js" ]