Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
    vb.name = "cliente.docker.prx.globalcare"
  end

  config.vm.define "zbxproxy" do |zbxproxy|

    zbxproxy.vm.network "public_network"#, ip: "192.168.1.25"
    #zbxproxy.vm.provision "shell",
    #  inline: "apt-get update && apt-get install -y puppet"
  end

end