version: '3.1'

networks:
  network-zabbix:
    driver: bridge

services:
  timescaledb:
    container_name: pgsql
    image: timescale/timescaledb:2.9.3-pg14
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - LANG=en_US.utf8
      - LANGUAGE=en_US.utf8
      - LC_ALL=en_US.utf8
      - LC_COLLATE=en_US.utf8
      - LC_CTYPE=en_US.utf8
      - TZ=GMT-3
    networks:
      - network-zabbix
    volumes:
      - /data/timescaledb:/var/lib/postgresql/data

  zabbix-server:
    container_name: zabbix-node01
    image: zabbix/zabbix-server-pgsql:alpine-6.2.7
    networks:
      - network-zabbix
    links:
      - timescaledb
    restart: always
    ports:
      - '10051:10051'
    volumes:
      - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
    environment:
      - DB_SERVER_HOST=pgsql
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - ZBX_SERVER_NAME=zsrv
      - ZBX_STARTPOLLERS=30
      - ZBX_STARTPOLLERSUNREACHABLE=15
      - ZBX_STARTTRAPPERS=20
      - ZBX_STARTPINGERS=15
      - ZBX_CACHESIZE=128M
      - ZBX_HISTORYCACHESIZE=32M
      - ZBX_HISTORYINDEXCACHESIZE=16M
      - ZBX_STARTVMWARECOLLECTORS=1
      - ZBX_VMWAREFREQUENCY=60
      - ZBX_VMWAREPERFFREQUENCY=60
      - ZBX_VMWARECACHESIZE=16M
      - ZBX_VMWARETIMEOUT=10 
      - ENABLE_TIMESCALEDB=true
      - ZBX_HANODENAME=zabbix-node01
      - ZBX_NODEADDRESS=zabbix-node01:10051
    depends_on:
      - timescaledb

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.2.7
    networks:
      - network-zabbix
    links:
      - timescaledb
      - zabbix-server
      #- zabbix-server2
    restart: always
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - DB_SERVER_HOST=pgsql
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - PHP_TZ=America/Sao_Paulo
      - ZBX_SERVER_NAME=ALFATEC
    volumes:
      - /data/custom/brand.conf.php:/usr/share/zabbix/local/conf/brand.conf.php

    depends_on:
      - timescaledb
   
  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
      - network-zabbix
    links:
      - timescaledb
      - zabbix-server
      #- zabbix-server2
      - zabbix-frontend
    restart: always
    ports:
      - '3000:3000'
    environment: 
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    depends_on:
      - timescaledb
      - zabbix-server
      #- zabbix-server2
    volumes:
      - /data/grafana:/var/lib/grafana
      #  - /data/custom/grafana.db:/var/lib/grafana/grafana.db

  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2:alpine-6.2.7
    user: root
    networks:
      - network-zabbix
    links:
      - zabbix-server
      #- zabbix-server2
      - zabbix-frontend
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
    ports:
      - '10050:10050'
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=zabbix-node01,zabbix-node02
