FROM zabbix/zabbix-proxy-sqlite3:6.0.26-ubuntu
USER root
RUN apt update
RUN apt install unzip curl wget gnupg2 libaio1 tdsodbc libgtk2.0-0 libgtk-3-0 snmp snmp-mibs-downloader telnet -y

#SNMP MIBs
RUN echo mibs +ALL >> /etc/snmp/snmp.conf && wget http://pastebin.com/raw.php?i=p3QyuXzZ -O /usr/share/snmp/mibs/ietf/SNMPv2-PDU

#MYSQL
ADD https://dev.mysql.com/get/Downloads/Connector-ODBC/8.0/mysql-connector-odbc-8.0.30-linux-glibc2.27-x86-64bit.tar.gz tmp/
RUN tar -xvf tmp/mysql-connector-odbc-8.0.30-linux-glibc2.27-x86-64bit.tar.gz -C /tmp \
&& cp /tmp/mysql-connector-odbc-8.0.30-linux-glibc2.27-x86-64bit/bin/myodbc-installer /usr/bin \
&& cp -R /tmp/mysql-connector-odbc-8.0.30-linux-glibc2.27-x86-64bit/lib/* /usr/local/lib \
&& rm -rf tmp/mysql-connector-odbc-8.0.30-linux-glibc2.27-x86-64bit.tar.gz
RUN myodbc-installer -a -d -n "MySQL ODBC 8.0 Driver" -t "Driver=/usr/local/lib/libmyodbc8w.so" \
&& myodbc-installer -a -d -n "MySQL ODBC 8.0" -t "Driver=/usr/local/lib/libmyodbc8a.so"
RUN apt install odbc-mariadb -y

#MSSQL
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
ADD https://packages.microsoft.com/config/ubuntu/22.04/prod.list /etc/apt/sources.list.d/msprod.list
RUN apt update && ACCEPT_EULA=Y apt install mssql-tools unixodbc-dev -y
RUN sed -i "1s/^./openssl\_conf\=\default\_conf/" /etc/ssl/openssl.cnf && sed -i '$a \\n\[default_conf\]\nssl\_conf\=\ssl\_sect\n\n\[ssl\_sect\]\nsystem\_default\=\system\_default\_sect\n\n[system\_default\_sect\]\nMinProtocol\=\TLSv1\nCipherString\=\DEFAULT\@SECLEVEL\=1' /etc/ssl/openssl.cnf

#POSTGRES
RUN apt install odbc-postgresql -y

#ORACLE
RUN mkdir /opt/oracle
ADD https://download.oracle.com/otn_software/linux/instantclient/instantclient-basic-linuxx64.zip /tmp
ADD https://download.oracle.com/otn_software/linux/instantclient/instantclient-odbc-linuxx64.zip /tmp
RUN unzip /tmp/instantclient-basic-linuxx64.zip -d /opt/oracle/ \
&& unzip /tmp/instantclient-odbc-linuxx64.zip -d /opt/oracle/ \
&& sh -c 'cd /opt/oracle/instantclient_21_8; ./odbc_update_ini.sh /.' \
&& sh -c "echo /opt/oracle/instantclient_21_8 > /etc/ld.so.conf.d/oracle-instantclient.conf" \
&& ldconfig

#REMOVER TEMP
RUN rm -rf /tmp/*
